[
  "Full Name",
  "Gender",
  "Birth Date",
  "City",
  "Country of Birth",
  "Username",
  "Email",
  "Type",
  "Role",
  "Experience Level",
  "Management Style",
  "Management Type",
  "Highest Coaching Education",
  "Club ID",
  "Team Name",
  "Team ID",
  "Status",
  "Team Image",
  "Contract Start Date",
  "Contract End Date",
  "Analytics",
  "Set Pieces",
  "Defending",
  "Player Development",
  "Turnovers",
  "Attacking",
  "Physics",
  "Tactics",
  "Mental",
  "Technics",
  "Left Foot",
  "Right Foot",
  "Height",
  "Weight",
  "Left Foot Length",
  "Right Foot Length",
  "Last Active",
  "Is Online",
  "Circle Completed",
  "Social Links",
  "Face Image",
  "Body Image",
  "Videos",
  "Verified",
  "Account Active",
  "Account Created At",
  "Account Expires At"
]
[
  "friendStatus",
  "followStatus",
  "isConfirmBox",
  "isFollowed",
  "isHead2Head",
  "activeSeasons",
  "textSEO",
  "totalTrophies",
  "totalAwards",
  "totalCaps",
  "lastUpdatedDate",
  "faceImageUrl",
  "starRating",
  "currentClubIconUrl",
  "contractedUntil",
  "managementType",
  "countryFlagUrl",
  "birthDay",
  "age",
  "summary",
  "topVideoLinks",
  "coachRadarSkills",
  "specialities",
  "userRole",
  "teamIds",
  "clubId",
  "clubs",
  "primaryTeam",
  "favoriteRoles"
]
